version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./app/.env
    volumes:
      - db_volume:/var/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./app/.env
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    build: .
    volumes:
      - ./app/:/code/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    command: "pdm run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

volumes:
  db_volume:
